/**
 * TCP API
 * API for TCP server
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAI_addunit_put_request.h
 *
 * 
 */

#ifndef OAI_addunit_put_request_H
#define OAI_addunit_put_request_H

#include <QJsonObject>

#include "OAI_addres_get_200_response_inner_peoples_inner.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAI_addres_get_200_response_inner_peoples_inner;

class OAI_addunit_put_request : public OAIObject {
public:
    OAI_addunit_put_request();
    OAI_addunit_put_request(QString json);
    ~OAI_addunit_put_request() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getCity() const;
    void setCity(const QString &city);
    bool is_city_Set() const;
    bool is_city_Valid() const;

    QString getStreet() const;
    void setStreet(const QString &street);
    bool is_street_Set() const;
    bool is_street_Valid() const;

    QList<OAI_addres_get_200_response_inner_peoples_inner> getPeoples() const;
    void setPeoples(const QList<OAI_addres_get_200_response_inner_peoples_inner> &peoples);
    bool is_peoples_Set() const;
    bool is_peoples_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString city;
    bool m_city_isSet;
    bool m_city_isValid;

    QString street;
    bool m_street_isSet;
    bool m_street_isValid;

    QList<OAI_addres_get_200_response_inner_peoples_inner> peoples;
    bool m_peoples_isSet;
    bool m_peoples_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAI_addunit_put_request)

#endif // OAI_addunit_put_request_H
