/**
 * TCP API
 * API for TCP server
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAI_addunit_put_request.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAI_addunit_put_request::OAI_addunit_put_request(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAI_addunit_put_request::OAI_addunit_put_request() {
    this->initializeModel();
}

OAI_addunit_put_request::~OAI_addunit_put_request() {}

void OAI_addunit_put_request::initializeModel() {

    m_city_isSet = false;
    m_city_isValid = false;

    m_street_isSet = false;
    m_street_isValid = false;

    m_peoples_isSet = false;
    m_peoples_isValid = false;
}

void OAI_addunit_put_request::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAI_addunit_put_request::fromJsonObject(QJsonObject json) {

    m_city_isValid = ::OpenAPI::fromJsonValue(city, json[QString("city")]);
    m_city_isSet = !json[QString("city")].isNull() && m_city_isValid;

    m_street_isValid = ::OpenAPI::fromJsonValue(street, json[QString("street")]);
    m_street_isSet = !json[QString("street")].isNull() && m_street_isValid;

    m_peoples_isValid = ::OpenAPI::fromJsonValue(peoples, json[QString("peoples")]);
    m_peoples_isSet = !json[QString("peoples")].isNull() && m_peoples_isValid;
}

QString OAI_addunit_put_request::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAI_addunit_put_request::asJsonObject() const {
    QJsonObject obj;
    if (m_city_isSet) {
        obj.insert(QString("city"), ::OpenAPI::toJsonValue(city));
    }
    if (m_street_isSet) {
        obj.insert(QString("street"), ::OpenAPI::toJsonValue(street));
    }
    if (peoples.size() > 0) {
        obj.insert(QString("peoples"), ::OpenAPI::toJsonValue(peoples));
    }
    return obj;
}

QString OAI_addunit_put_request::getCity() const {
    return city;
}
void OAI_addunit_put_request::setCity(const QString &city) {
    this->city = city;
    this->m_city_isSet = true;
}

bool OAI_addunit_put_request::is_city_Set() const{
    return m_city_isSet;
}

bool OAI_addunit_put_request::is_city_Valid() const{
    return m_city_isValid;
}

QString OAI_addunit_put_request::getStreet() const {
    return street;
}
void OAI_addunit_put_request::setStreet(const QString &street) {
    this->street = street;
    this->m_street_isSet = true;
}

bool OAI_addunit_put_request::is_street_Set() const{
    return m_street_isSet;
}

bool OAI_addunit_put_request::is_street_Valid() const{
    return m_street_isValid;
}

QList<OAI_addres_get_200_response_inner_peoples_inner> OAI_addunit_put_request::getPeoples() const {
    return peoples;
}
void OAI_addunit_put_request::setPeoples(const QList<OAI_addres_get_200_response_inner_peoples_inner> &peoples) {
    this->peoples = peoples;
    this->m_peoples_isSet = true;
}

bool OAI_addunit_put_request::is_peoples_Set() const{
    return m_peoples_isSet;
}

bool OAI_addunit_put_request::is_peoples_Valid() const{
    return m_peoples_isValid;
}

bool OAI_addunit_put_request::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_city_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_street_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (peoples.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAI_addunit_put_request::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
