/**
 * TCP API
 * API for TCP server
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIDefaultApi_H
#define OAI_OAIDefaultApi_H

#include "OAIHelpers.h"
#include "OAIHttpRequest.h"
#include "OAIServerConfiguration.h"
#include "OAIOauth.h"

#include "OAI_addres_get_200_response_inner.h"
#include "OAI_addunit_put_request.h"
#include <QString>

#include <QObject>
#include <QByteArray>
#include <QStringList>
#include <QList>
#include <QNetworkAccessManager>

namespace OpenAPI {

class OAIDefaultApi : public QObject {
    Q_OBJECT

public:
    OAIDefaultApi(const int timeOut = 0);
    ~OAIDefaultApi();

    void initializeServerConfigs();
    int setDefaultServerValue(int serverIndex,const QString &operation, const QString &variable,const QString &val);
    void setServerIndex(const QString &operation, int serverIndex);
    void setApiKey(const QString &apiKeyName, const QString &apiKey);
    void setBearerToken(const QString &token);
    void setUsername(const QString &username);
    void setPassword(const QString &password);
    void setTimeOut(const int timeOut);
    void setWorkingDirectory(const QString &path);
    void setNetworkAccessManager(QNetworkAccessManager* manager);
    int addServerConfiguration(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables = QMap<QString, OAIServerVariable>());
    void setNewServerForAllOperations(const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables =  QMap<QString, OAIServerVariable>());
    void setNewServer(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables =  QMap<QString, OAIServerVariable>());
    void addHeaders(const QString &key, const QString &value);
    void enableRequestCompression();
    void enableResponseCompression();
    void abortRequests();
    QString getParamStylePrefix(const QString &style);
    QString getParamStyleSuffix(const QString &style);
    QString getParamStyleDelimiter(const QString &style, const QString &name, bool isExplode);


    void addresGet();

    /**
    * @param[in]  oai_addunit_put_request OAI_addunit_put_request [optional]
    */
    void addunitPut(const ::OpenAPI::OptionalParam<OAI_addunit_put_request> &oai_addunit_put_request = ::OpenAPI::OptionalParam<OAI_addunit_put_request>());


    void alldelDelete();

    /**
    * @param[in]  adname QString [required]
    */
    void deleteuserfornameAdnameDelete(const QString &adname);


private:
    QMap<QString,int> _serverIndices;
    QMap<QString,QList<OAIServerConfiguration>> _serverConfigs;
    QMap<QString, QString> _apiKeys;
    QString _bearerToken;
    QString _username;
    QString _password;
    int _timeOut;
    QString _workingDirectory;
    QNetworkAccessManager* _manager;
    QMap<QString, QString> _defaultHeaders;
    bool _isResponseCompressionEnabled;
    bool _isRequestCompressionEnabled;
    OAIHttpRequestInput _latestInput;
    OAIHttpRequestWorker *_latestWorker;
    QStringList _latestScope;
    OauthCode _authFlow;
    OauthImplicit _implicitFlow;
    OauthCredentials _credentialFlow;
    OauthPassword _passwordFlow;
    int _OauthMethod = 0;

    void addresGetCallback(OAIHttpRequestWorker *worker);
    void addunitPutCallback(OAIHttpRequestWorker *worker);
    void alldelDeleteCallback(OAIHttpRequestWorker *worker);
    void deleteuserfornameAdnameDeleteCallback(OAIHttpRequestWorker *worker);

signals:

    void addresGetSignal(QList<OAI_addres_get_200_response_inner> summary);
    void addunitPutSignal();
    void alldelDeleteSignal();
    void deleteuserfornameAdnameDeleteSignal();

    void addresGetSignalFull(OAIHttpRequestWorker *worker, QList<OAI_addres_get_200_response_inner> summary);
    void addunitPutSignalFull(OAIHttpRequestWorker *worker);
    void alldelDeleteSignalFull(OAIHttpRequestWorker *worker);
    void deleteuserfornameAdnameDeleteSignalFull(OAIHttpRequestWorker *worker);

    void addresGetSignalE(QList<OAI_addres_get_200_response_inner> summary, QNetworkReply::NetworkError error_type, QString error_str);
    void addunitPutSignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void alldelDeleteSignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void deleteuserfornameAdnameDeleteSignalE(QNetworkReply::NetworkError error_type, QString error_str);

    void addresGetSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void addunitPutSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void alldelDeleteSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void deleteuserfornameAdnameDeleteSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);

    void abortRequestsSignal();
    void allPendingRequestsCompleted();

public slots:
    void tokenAvailable();
    
};

} // namespace OpenAPI
#endif
