# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.addres_peoples import AddresPeoples  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, city: str=None, street: str=None, peoples: List[AddresPeoples]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param city: The city of this InlineResponse200.  # noqa: E501
        :type city: str
        :param street: The street of this InlineResponse200.  # noqa: E501
        :type street: str
        :param peoples: The peoples of this InlineResponse200.  # noqa: E501
        :type peoples: List[AddresPeoples]
        """
        self.swagger_types = {
            'city': str,
            'street': str,
            'peoples': List[AddresPeoples]
        }

        self.attribute_map = {
            'city': 'city',
            'street': 'street',
            'peoples': 'peoples'
        }
        self._city = city
        self._street = street
        self._peoples = peoples

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def city(self) -> str:
        """Gets the city of this InlineResponse200.


        :return: The city of this InlineResponse200.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city: str):
        """Sets the city of this InlineResponse200.


        :param city: The city of this InlineResponse200.
        :type city: str
        """

        self._city = city

    @property
    def street(self) -> str:
        """Gets the street of this InlineResponse200.


        :return: The street of this InlineResponse200.
        :rtype: str
        """
        return self._street

    @street.setter
    def street(self, street: str):
        """Sets the street of this InlineResponse200.


        :param street: The street of this InlineResponse200.
        :type street: str
        """

        self._street = street

    @property
    def peoples(self) -> List[AddresPeoples]:
        """Gets the peoples of this InlineResponse200.


        :return: The peoples of this InlineResponse200.
        :rtype: List[AddresPeoples]
        """
        return self._peoples

    @peoples.setter
    def peoples(self, peoples: List[AddresPeoples]):
        """Sets the peoples of this InlineResponse200.


        :param peoples: The peoples of this InlineResponse200.
        :type peoples: List[AddresPeoples]
        """

        self._peoples = peoples
